import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "JaMoveo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-full p-4 sm:p-6 md:p-8 lg:p-10 xl:p-12 bg-gray-800 text-white">
          <h1 className="text-lg sm:text-xl md:text-2xl lg:text-3xl xl:text-4xl font-bold">
            Welcome to JaMoveo 🎶
          </h1>
          <p className="text-sm md:text-base lg:text-lg">
            Your real-time band rehearsal assistant!
          </p>
        </div>
        {children}
      </body>
    </html>
  );
}
